.\" Copyright (C) 2020 Ryan Kavanagh <rak@debian.org>
.\" All rights reserved.
.\" Permission to use, copy, modify, and distribute this software for any
.\" purpose with or without fee is hereby granted, provided that the above
.\" copyright notice and this permission notice appear in all copies.
.\"
.\" THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
.\" WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
.\" MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
.\" ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
.\" WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
.\" ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
.\" OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
.Dd April 12, 2020
.Dt FILTER-DNSBLSCORE 8
.Os
.Sh NAME
.Nm filter-dnsblscore
.Nd DNSBL filter for OpenSMTPD
.Sh SYNOPSIS
.Nm filter-dnsblscore
.Op Fl blockAbove Ar score
.Op Fl blockPhase Ar phase
.Op Fl junkAbove  Ar score
.Op Fl slowFactor Ar factor
.Op Fl scoreHeader
.Ar <domain>:<weight>...
.Sh DESCRIPTION
The
.Nm
filter for the OpenSMTPD
.Pq Xr smtpd 8
server filters sessions based on DNSBL queries. Each blocklist can be assigned
a positive weight, and each connecting IP address is assigned a score
calculated as the sum of the weights of blocklists the IP address is found on.
Options are:
.Bl -tag -width scoreHeader
.It Fl blockAbove Ar score
Displays an error banner for sessions with a score higher than
.Ar score
and then disconnects.
.It Fl blockPhase Ar phase
Determines at which phase
.Fl blockAbove
is triggered.
The default is
.Ar connect .
Valid choices are
.Ar connect ,
.Ar helo ,
.Ar ehlo ,
.Ar starttls ,
.Ar auth ,
.Ar mail-from ,
.Ar rcpt-to ,
and
.Ar quit .
Note that
.Ar quit
will result in a message at the end of a session and may only be used to warn
the sender that its score is degrading, as it will not prevent transactions
from succeeding.
.It Fl junkAbove Ar score
Prepends a
.Ql X-Spam: yes
header to messages for sessions with a score higher than
.Ar score .
.It Fl slowFactor Ar factor
Delays all answers by this many milliseconds, where
.Ql score
is the blocklist score and
.Ql maxScore
is the sum of all blocklist weights.
.Dl factor \(** score \(di maxScore
.It Fl scoreHeader
Adds an
.Ql X-DNSBL-Score
header with the sender's blocklist score if known.
.El
.Sh EXIT STATUS
.Ex -std
.Sh EXAMPLES
Adding the following to
.Pa smtpd.conf
enables
.Nm
for all incoming connections.
.Bd -literal
filter "dnsblscore" proc-exec \\
       "/usr/local/bin/filter-dnsblscore -blockAbove 50 \\
                                         -junkAbove  0 \\
                                         -slowFactor 1000 \\
                                         b.barracudacentral.org:60 \\
                                         bl.spamcop.net:40"

listen on all filter "dnsblscore"
.Ed
.Sh SEE ALSO
.Xr smtpd.conf 5
.Sh AUTHORS
.Nm
is Copyright \(co 2025
.An -nosplit
.An Lukas Fleischer Aq Mt lfleischer@lfos.de
and Copyright \(co 2019-2021
.An -nosplit
.An Gilles Chehade Aq Mt gilles@poolp.org .
This man page is Copyright \(co 2020
.An Ryan Kavanagh Aq Mt rak@debian.org .
Both are distributed under the ISC license.
.Sh BUGS
None known.
